# -*- coding: utf-8 -*-
"""Movie_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d12TttivxFZSpZZFXgOQuYpBaTcOvvb6
"""

import pandas as pd

df=pd.read_csv('/content/imdb_movie_dataset.csv')

df.info()

df.describe()

df.head(2)

df.tail(5)

df.isnull().sum()

missing_value=(df.isnull().sum()/len(df))*100
print(missing_value)

df['Revenue (Millions)']=df['Revenue (Millions)'].fillna(df['Revenue (Millions)'].median())

df['Metascore']=df['Metascore'].fillna(df['Metascore'].median())

df.duplicated().sum()

df.drop_duplicates(inplace=True)

tar="Rating"
ncol=df.select_dtypes(include=['float64','int64']).columns
for col in ncol:
  if col!=tar:
    val=df[tar].corr(df[col])
    print(f"{tar} vs {col}: {val:.2f}")

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/imdb_movie_dataset.csv")

top10_revenue = df.sort_values('Revenue (Millions)', ascending=False).head(10)

plt.figure(figsize=(10,6))
plt.bar(top10_revenue['Title'], top10_revenue['Revenue (Millions)'], color='steelblue')
plt.title('Top 10 Highest Grossing Movies', fontsize=14)
plt.xlabel('Movie Title')
plt.ylabel('Revenue (Millions)')
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/imdb_movie_dataset.csv")

plt.figure(figsize=(8,6))
plt.hist(df['Rating'], bins=20, color='skyblue', edgecolor='black')
plt.title('Rating Distribution', fontsize=14)
plt.xlabel('Rating')
plt.ylabel('Number of Movies')
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/imdb_movie_dataset.csv")

plt.figure(figsize=(8,6))
plt.scatter(df['Votes'], df['Rating'], alpha=0.5, color='darkorange')
plt.title('Votes vs Rating', fontsize=14)
plt.xlabel('Votes')
plt.ylabel('Rating')
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/imdb_movie_dataset.csv")

yearly_avg = df.groupby('Year')['Rating'].mean()

plt.figure(figsize=(10,6))
plt.plot(yearly_avg.index, yearly_avg.values, marker='o', color='green')
plt.title('Average Rating by Year', fontsize=14)
plt.xlabel('Year')
plt.ylabel('Average Rating')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()